Repository Mirou-KnJ/Mirou_Main, pull requests merged in 2023-12, with the labels that each got.

#127 물건, 상점 관련 기본 시나리오 구성
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/inventory/entity/Inventory.java
  src/main/java/com/knj/mirou/boundedContext/product/controller/ProductController.java
  src/main/java/com/knj/mirou/boundedContext/product/controller/ProductInfoController.java
  src/main/java/com/knj/mirou/boundedContext/product/model/entity/Product.java
  src/main/java/com/knj/mirou/boundedContext/product/model/entity/ProductInfo.java
  src/main/java/com/knj/mirou/boundedContext/product/model/enums/ProductStatus.java
  src/main/java/com/knj/mirou/boundedContext/product/repository/ProductInfoRepository.java
  src/main/java/com/knj/mirou/boundedContext/product/repository/ProductRepository.java
  src/main/java/com/knj/mirou/boundedContext/product/service/ProductInfoService.java
  src/main/java/com/knj/mirou/boundedContext/product/service/ProductService.java
  src/main/java/com/knj/mirou/boundedContext/store/controller/StoreController.java
  src/main/java/com/knj/mirou/boundedContext/store/model/enums/SaleType.java
  src/main/java/com/knj/mirou/boundedContext/store/repository/StoreRepository.java
  src/main/java/com/knj/mirou/boundedContext/store/service/StoreService.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/common/layout/defaultLayout.html
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/product/codeAddForm.html
  src/main/resources/templates/view/product/infoAddForm.html
  src/main/resources/templates/view/product/store.html
  src/main/resources/templates/view/store/addForm.html
  src/main/resources/templates/view/store/storePage.html
Labels: enhancement, refactoring

#130 챌린지 도메인 리팩토링
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/dtos/ChallengeDetailDTO.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/AuthenticationMethod.java
  src/main/java/com/knj/mirou/boundedContext/challenge/repository/ChallengeRepository.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/service/ImageDataService.java
  src/main/java/com/knj/mirou/boundedContext/inventory/entity/Inventory.java
  src/main/java/com/knj/mirou/boundedContext/product/controller/ProductController.java
  src/main/resources/application.yml
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/view/challenge/list.html
Labels: refactoring

#134 ChallengeMember, Member 리팩토링
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/member/config/MemberConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/member/repository/MemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/resources/templates/view/member/myPage.html
Labels: refactoring

#137 Coin, Point 관련사항 리팩토링
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/coin/config/CoinConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/coin/service/CoinService.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/controller/CoinHistoryController.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/entity/CoinHistory.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/repository/CoinHistoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/service/CoinHistoryService.java
  src/main/java/com/knj/mirou/boundedContext/member/repository/MemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/point/config/PointConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/point/entity/Point.java
  src/main/java/com/knj/mirou/boundedContext/point/service/PointService.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/controller/PointHistoryController.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/entity/PointHistory.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/service/PointHistoryService.java
Labels: refactoring

#139 상품, 상점 관련 리팩토링 및 프론트 개선 작업
  src/main/java/com/knj/mirou/boundedContext/inventory/controller/InventoryController.java
  src/main/java/com/knj/mirou/boundedContext/inventory/model/entity/Inventory.java
  src/main/java/com/knj/mirou/boundedContext/inventory/model/enums/InventoryStatus.java
  src/main/java/com/knj/mirou/boundedContext/inventory/repository/InventoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/inventory/service/InventoryService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/member/model/entity/Member.java
  src/main/java/com/knj/mirou/boundedContext/product/controller/ProductController.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/common/layout/exampleLayout.default
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/member/inventory.html
  src/main/resources/templates/view/product/codeAddForm.html
  src/main/resources/templates/view/product/infoAddForm.html
  src/main/resources/templates/view/product/store.html
Labels: refactoring, Front

#141 리스트 내가 완료한 챌린지 출력 오류 해결
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
Labels: bug

#143 프론트 레이아웃 틀 변경 및 적용
  src/main/resources/templates/common/layout/defaultLayout.html
  src/main/resources/templates/common/layout/exampleLayout.default
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challenge/list.html
  src/main/resources/templates/view/challenge/mapTest.html
  src/main/resources/templates/view/challengeFeed/list.html
  src/main/resources/templates/view/challengeFeed/mapWriteForm.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
  src/main/resources/templates/view/coin/history.html
  src/main/resources/templates/view/index.html
  src/main/resources/templates/view/member/inventory.html
  src/main/resources/templates/view/member/login.html
  src/main/resources/templates/view/member/myPage.html
  src/main/resources/templates/view/point/history.html
  src/main/resources/templates/view/product/codeAddForm.html
  src/main/resources/templates/view/product/infoAddForm.html
  src/main/resources/templates/view/product/store.html
  src/main/resources/templates/view/reward/confirmForm.html
  src/main/resources/templates/view/reward/settingForm.html
  src/main/resources/templates/view/store/addForm.html
  src/main/resources/templates/view/store/storePage.html
Labels: Front

#146 전체 프론트 디자인 변경 및 정렬
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/AuthenticationMethod.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengeTag.java
  src/main/resources/static/common/common.css
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challenge/list.html
  src/main/resources/templates/view/challengeFeed/mapWriteForm.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
  src/main/resources/templates/view/coin/history.html
  src/main/resources/templates/view/index.html
  src/main/resources/templates/view/member/inventory.html
  src/main/resources/templates/view/member/myPage.html
  src/main/resources/templates/view/point/history.html
  src/main/resources/templates/view/reward/confirmForm.html
  src/main/resources/templates/view/reward/settingForm.html
Labels: Front

#152 confirm reward 오류 수정
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/resources/templates/view/reward/confirmForm.html
Labels: bug

#153 마이페이지 프론트 변경 및 전체 페이지 본문 테두리 설정
  src/main/java/com/knj/mirou/boundedContext/product/controller/ProductController.java
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challenge/list.html
  src/main/resources/templates/view/challengeFeed/list.html
  src/main/resources/templates/view/challengeFeed/mapWriteForm.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
  src/main/resources/templates/view/coin/history.html
  src/main/resources/templates/view/index.html
  src/main/resources/templates/view/member/inventory.html
  src/main/resources/templates/view/member/login.html
  src/main/resources/templates/view/member/myPage.html
  src/main/resources/templates/view/point/history.html
  src/main/resources/templates/view/product/codeAddForm.html
  src/main/resources/templates/view/product/infoAddForm.html
  src/main/resources/templates/view/product/store.html
  src/main/resources/templates/view/reward/confirmForm.html
  src/main/resources/templates/view/reward/settingForm.html
Labels: Front

#154 피드 리스트 프론트 작업 및 프론트 마무리 수정
  src/main/java/com/knj/mirou/boundedContext/challengefeed/model/dtos/FeedListDTO.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/model/entity/ChallengeFeed.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/service/ImageDataService.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challenge/list.html
  src/main/resources/templates/view/challengeFeed/list.html
  src/main/resources/templates/view/member/myPage.html
  src/main/resources/templates/view/product/store.html
Labels: Front

#156 Fix: 파일 최대 크기 조정
  src/main/resources/application.yml
Labels: bug

#157 신고기능 추가구현 및 패널티 부여
  src/main/java/com/knj/mirou/boundedContext/challengefeed/model/entity/ChallengeFeed.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/model/enums/FeedStatus.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/repository/ChallengeFeedRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/coin/config/CoinConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/coin/service/CoinService.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/point/service/PointService.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/controller/ReportHistoryController.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/entity/ReportHistory.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/service/ReportHistoryService.java
  src/main/resources/application-secret.default
  src/main/resources/templates/view/challengeFeed/list.html
Labels: enhancement

#167 알림 기능 시나리오 구현
  src/main/java/com/knj/mirou/base/event/EventAfterBuyProduct.java
  src/main/java/com/knj/mirou/base/event/EventAfterEndProgress.java
  src/main/java/com/knj/mirou/base/event/EventAfterGiveCoin.java
  src/main/java/com/knj/mirou/base/event/EventAfterJoin.java
  src/main/java/com/knj/mirou/base/event/EventAfterJoinChallenge.java
  src/main/java/com/knj/mirou/base/event/EventAfterResetPoint.java
  src/main/java/com/knj/mirou/base/event/EventAfterWriteFeed.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/coin/eventListener/CoinEventListener.java
  src/main/java/com/knj/mirou/boundedContext/coin/service/CoinService.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/service/CoinHistoryService.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/notification/controller/NotificationController.java
  src/main/java/com/knj/mirou/boundedContext/notification/eventListener/NotificationEventListener.java
  src/main/java/com/knj/mirou/boundedContext/notification/model/entity/Notification.java
  src/main/java/com/knj/mirou/boundedContext/notification/model/enums/NotiType.java
  src/main/java/com/knj/mirou/boundedContext/notification/repository/NotificationRepository.java
  src/main/java/com/knj/mirou/boundedContext/notification/service/NotificationService.java
  src/main/java/com/knj/mirou/boundedContext/point/service/PointService.java
  src/main/java/com/knj/mirou/boundedContext/product/service/ProductService.java
  src/main/resources/templates/view/member/myPage.html
  src/main/resources/templates/view/notification/list.html
Labels: enhancement

#169 챌린지 인증 유형 라벨 추가
  src/main/java/com/knj/mirou/boundedContext/challenge/config/LabelConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengeLabel.java
  src/main/resources/application-secret.default
Labels: documentation

#171 로그인페이지 이용약관 추가
  src/main/resources/templates/view/member/login.html
Labels: Front

#172 챌린지 태그 추가 및 프론트 수정
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengeTag.java
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challenge/list.html
Labels: refactoring, Front

#173 관리자 통계 1차 작업 (챌린지 통계, 화폐 통계, 물품 통계 1차작업)
  src/main/java/com/knj/mirou/boundedContext/challengefeed/repository/ChallengeFeedRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/repository/CoinHistoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/service/CoinHistoryService.java
  src/main/java/com/knj/mirou/boundedContext/inventory/repository/InventoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/inventory/service/InventoryService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/AdminController.java
  src/main/java/com/knj/mirou/boundedContext/member/model/dtos/ChallengeReportDTO.java
  src/main/java/com/knj/mirou/boundedContext/member/model/dtos/CurrencyReportDTO.java
  src/main/java/com/knj/mirou/boundedContext/member/model/dtos/ProductReportDTO.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/repository/PointHistoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/service/PointHistoryService.java
  src/main/java/com/knj/mirou/boundedContext/product/controller/ProductController.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/admin/report/challengeReport.html
  src/main/resources/templates/view/admin/report/currencyReport.html
  src/main/resources/templates/view/admin/report/index.html
  src/main/resources/templates/view/admin/report/productReport.html
Labels: enhancement

#176 관리자 통계 2차 기능 및 신고 내역 관리
  src/main/java/com/knj/mirou/base/event/EventAfterKickedChallenge.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/service/CoinHistoryService.java
  src/main/java/com/knj/mirou/boundedContext/inventory/service/InventoryService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/AdminController.java
  src/main/java/com/knj/mirou/boundedContext/member/model/dtos/ReportManageDTO.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/notification/eventListener/NotificationEventListener.java
  src/main/java/com/knj/mirou/boundedContext/notification/model/enums/NotiType.java
  src/main/java/com/knj/mirou/boundedContext/notification/service/NotificationService.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/service/PointHistoryService.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/entity/ReportHistory.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/repository/ReportHistoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/service/ReportHistoryService.java
  src/main/resources/templates/view/admin/report/index.html
  src/main/resources/templates/view/admin/report/productReport.html
  src/main/resources/templates/view/admin/report/reportManage.html
Labels: enhancement, refactoring

#177 로그인페이지 텍스트 위치조정
  src/main/resources/templates/view/index.html
  src/main/resources/templates/view/member/login.html
Labels: Front

#178 챌린지 생성 시 라벨 유형 추가 및 라디오버튼 -> selectbox로 변경
  src/main/resources/templates/view/challenge/createForm.html
Labels: refactoring

#180 라벨, 태그 하드코딩 개선
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengeLabel.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/resources/templates/view/challenge/createForm.html
Labels: refactoring

#181 닉네임, 프로필 이미지 변경
  src/main/java/com/knj/mirou/boundedContext/imageData/model/enums/OptimizerOption.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/member/model/entity/Member.java
  src/main/java/com/knj/mirou/boundedContext/member/repository/MemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/resources/templates/view/admin/report/reportManage.html
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challengeFeed/list.html
  src/main/resources/templates/view/member/myPage.html
Labels: enhancement

#183 피드 숨김처리 및 긴 콘텐츠들 줄바꿈 관리
  src/main/java/com/knj/mirou/base/util/Ut.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/product/service/ProductInfoService.java
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challengeFeed/list.html
  src/main/resources/templates/view/member/inventory.html
  src/main/resources/templates/view/product/infoAddForm.html
  src/main/resources/templates/view/reward/confirmForm.html
Labels: refactoring

#184 보상 수정 및 삭제 기능 추가
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/java/com/knj/mirou/boundedContext/reward/model/entity/PublicReward.java
  src/main/java/com/knj/mirou/boundedContext/reward/repository/PublicRewardRepository.java
  src/main/java/com/knj/mirou/boundedContext/reward/service/PublicRewardService.java
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/reward/settingForm.html
Labels: enhancement

#186 프론트 최종 다듬기(1)
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/point/service/PointService.java
  src/main/resources/templates/view/admin/report/challengeReport.html
  src/main/resources/templates/view/admin/report/currencyReport.html
  src/main/resources/templates/view/admin/report/productReport.html
  src/main/resources/templates/view/admin/report/reportManage.html
  src/main/resources/templates/view/challengeFeed/list.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
Labels: Front

#187 에러페이지 렌더링
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/error/5xx.html
Labels: enhancement

#192 챌린지 관련 도메인 서비스 단위 테스트
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/resources/static/img/not_water.png
  src/main/resources/static/img/sampleTXT.txt
  src/main/resources/static/img/test_water.png
  src/test/java/com/knj/mirou/boundedContext/challenge/service/ChallengeServiceTest.java
  src/test/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedServiceTest.java
  src/test/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberServiceTest.java
Labels: test

#200 보상 확인 폼 프론트 수정
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challengeFeed/mapWriteForm.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
  src/main/resources/templates/view/product/codeAddForm.html
  src/main/resources/templates/view/product/infoAddForm.html
  src/main/resources/templates/view/product/store.html
  src/main/resources/templates/view/reward/confirmForm.html
  src/main/resources/templates/view/reward/settingForm.html
Labels: Front
