Repository Mirou-KnJ/Mirou_Main, pull requests merged in 2023-11, with the labels that each got.

#19 프론트(마이페이지, 회원가입, 인덱스 페이지) 작업
  src/main/java/com/knj/mirou/base/controller/HomeController.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/images/img1.jpg
  src/main/resources/templates/view/member/login.html
  src/main/resources/templates/view/member/mypage.html
Labels: enhancement

#20 카카오 로그인 기능 구현
  build.gradle
  src/main/java/com/knj/mirou/base/security/CustomOAuth2UserService.java
  src/main/java/com/knj/mirou/base/security/CustomUserDetailsService.java
  src/main/java/com/knj/mirou/base/security/SecurityConfig.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/coin/entity/Coin.java
  src/main/java/com/knj/mirou/boundedContext/coin/repository/CoinRepository.java
  src/main/java/com/knj/mirou/boundedContext/coin/service/CoinService.java
  src/main/java/com/knj/mirou/boundedContext/image/model/enums/ImageTarget.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/member/model/entity/Member.java
  src/main/java/com/knj/mirou/boundedContext/member/model/enums/SocialCode.java
  src/main/java/com/knj/mirou/boundedContext/member/repository/MemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/point/entity/Point.java
  src/main/java/com/knj/mirou/boundedContext/point/repository/PointRepository.java
  src/main/java/com/knj/mirou/boundedContext/point/service/PointService.java
  src/main/java/com/knj/mirou/boundedContext/product/model/entity/Product.java
  src/main/resources/application-secret.default
  src/main/resources/application.yml
  src/main/resources/templates/view/index.html
Labels: enhancement

#23 프론트 리팩토링(마이페이지, 인덱스, 로그인)
  src/main/java/com/knj/mirou/base/controller/HomeController.java
  src/main/java/com/knj/mirou/base/security/SecurityConfig.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/resources/static/common/common.css
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/common/layout/exampleLayout.default
  src/main/resources/templates/images/img1.jpg
  src/main/resources/templates/view/index.html
  src/main/resources/templates/view/member/login.html
  src/main/resources/templates/view/member/mypage.html
Labels: enhancement, refactoring

#25 특정 유저 관리자 권한 부여 및 관리자 한정 동작
  src/main/java/com/knj/mirou/base/security/CustomOAuth2UserService.java
  src/main/java/com/knj/mirou/base/security/CustomUserDetailsService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/member/config/MemberConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/member/model/entity/Member.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/resources/application-secret.default
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/index.html
Labels: enhancement, refactoring

#30 인증하기 서비스를 위한 이미지 업로드, 라벨 검출, 유해성 검사
  .gitignore
  build.gradle
  src/main/java/com/knj/mirou/base/security/SecurityConfig.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedRestController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/image/config/GcpAuthConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/image/config/ImageConfig.java
  src/main/java/com/knj/mirou/boundedContext/image/config/S3ConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/image/service/ImageService.java
  src/main/resources/application-secret.default
  src/main/resources/templates/view/challengefeed/writeForm.html
  src/main/resources/templates/view/index.html
Labels: enhancement

#35 Reward, Challenge 리팩토링 및 챌린지별 보상 설정, NotProd를 통한 초기 데이터 생성
  src/main/java/com/knj/mirou/base/controller/HomeController.java
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengePeriod.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengeStatus.java
  src/main/java/com/knj/mirou/boundedContext/challenge/repository/ChallengeRepository.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/java/com/knj/mirou/boundedContext/reward/model/entity/PrivateReward.java
  src/main/java/com/knj/mirou/boundedContext/reward/model/entity/PublicReward.java
  src/main/java/com/knj/mirou/boundedContext/reward/model/enums/RewardType.java
  src/main/java/com/knj/mirou/boundedContext/reward/repository/PublicRewardRepository.java
  src/main/java/com/knj/mirou/boundedContext/reward/service/PublicRewardService.java
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/challenge/createChallenge.html
  src/main/resources/templates/view/reward/settingForm.html
Labels: enhancement, refactoring

#37 챌린지 전체 리스트 보기 기능구현
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/resources/templates/view/challenge/allChallengeList.html
Labels: enhancement

#38 Challenge에 참여하고, 인증글을 써보는 간단한 시나리오 구현
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedRestController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/repository/ChallengeFeedRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/challenge/allChallengeList.html
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challenge/detailChallenge.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
Labels: enhancement

#44 인증 이미지 세세한 처리와 피드 생성 및 피드 프론트 출력
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/base/rsData/RsData.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/repository/ChallengeFeedRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/model/entity/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/config/GcpAuthConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/imageData/config/ImageConfig.java
  src/main/java/com/knj/mirou/boundedContext/imageData/config/S3ConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/imageData/model/entity/ImageData.java
  src/main/java/com/knj/mirou/boundedContext/imageData/model/enums/ImageTarget.java
  src/main/java/com/knj/mirou/boundedContext/imageData/repository/ImageDataRepository.java
  src/main/java/com/knj/mirou/boundedContext/imageData/service/ImageDataService.java
  src/main/resources/application.yml
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challengeFeed/detail.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
Labels: enhancement, refactoring, Front

#49 챌린지 이미지 추가 및 디테일 페이지 출력, 챌린지 생성 페이지 프론트 개선
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/service/ImageDataService.java
  src/main/resources/templates/view/challenge/createChallenge.html
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challenge/detail.html
Labels: enhancement, Front

#51 챌린지 디테일 페이지 프론트 1차 완료
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/imageData/config/S3ConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/imageData/model/enums/OptimizerOption.java
  src/main/java/com/knj/mirou/boundedContext/imageData/service/ImageDataService.java
  src/main/resources/application-secret.default
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challenge/detail.html
Labels: refactoring, Front

#56 배포시 발생한 뷰 경로 오류 해결
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
Labels: bug

#57 챌린지 3회 참여제한
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/model/entity/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/resources/templates/view/challenge/detail.html
Labels: refactoring

#60 챌린지 오픈 처리
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challenge/repository/ChallengeRepository.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/challenge/list.html
  src/main/resources/templates/view/reward/confirmForm.html
  src/main/resources/templates/view/reward/settingForm.html
Labels: refactoring

#62 PrivateReward 객체 생성 및 저장, 디테일 페이지에서 참여 여부에 따라 다르게 노출
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/model/entity/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/reward/model/entity/PrivateReward.java
  src/main/java/com/knj/mirou/boundedContext/reward/repository/PrivateRewardRepository.java
  src/main/java/com/knj/mirou/boundedContext/reward/service/PrivateRewardService.java
  src/main/resources/templates/view/challenge/detail.html
Labels: enhancement, refactoring

#64 회원이 챌린지에 하루에 한번만 인증할 수 있도록
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/repository/ChallengeFeedRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/resources/application.yml
  src/main/resources/templates/view/challenge/detail.html
Labels: refactoring

#67 성공 횟수에 맞는 리워드 제공, 마지막 리워드 획득시 진행 종료
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/repository/ChallengeFeedRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/model/entity/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/coin/service/CoinService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/member/model/entity/Member.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/java/com/knj/mirou/boundedContext/reward/repository/PrivateRewardRepository.java
  src/main/java/com/knj/mirou/boundedContext/reward/service/PrivateRewardService.java
Labels: enhancement, refactoring

#68 코인 확률 조정 알고리즘
  src/main/java/com/knj/mirou/boundedContext/coin/service/CoinService.java
Labels: enhancement

#69 마이페이지 챌린지 내용 null 오류 해결
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/resources/templates/view/member/mypage.html
Labels: bug

#72 챌린지 디테일 페이지 프론트 작업
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/resources/templates/view/challenge/detail.html
Labels: Front

#74 챌린지 인증 페이지 프론트 작업
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/resources/templates/view/challengeFeed/writeForm.html
Labels: Front

#75 챌린지 서비스 리팩토링 및 일부 유효성 검사
  build.gradle
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/dtos/ChallengeCreateDTO.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/dtos/ChallengeDetailDTO.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challenge/repository/ChallengeRepository.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/repository/ChallengeFeedRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/service/ImageDataService.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/java/com/knj/mirou/boundedContext/reward/service/PrivateRewardService.java
  src/main/java/com/knj/mirou/boundedContext/reward/service/PublicRewardService.java
  src/main/resources/application.yml
  src/main/resources/templates/view/challenge/detail.html
Labels: refactoring

#77 ChallengeFeed 1차 리팩토링 작업
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/dtos/ChallengeDetailDTO.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/entity/ChallengeFeed.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/service/ImageDataService.java
Labels: refactoring

#79 ChallengeMember 리팩토링
  src/main/java/com/knj/mirou/boundedContext/challengemember/config/CMemberConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/model/entity/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/resources/application-secret.default
Labels: refactoring

#81 Coin 도메인 리팩토링 및 획득시 CoinHistory 간단 생성 시나리오 구현
  src/main/java/com/knj/mirou/boundedContext/coin/config/CoinConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/coin/service/CoinService.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/repository/CoinHistoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/service/CoinHistoryService.java
  src/main/resources/application-secret.default
Labels: enhancement, refactoring

#83 MemberService 리팩토링 및 관리자 페이지 수정
  src/main/java/com/knj/mirou/base/security/CustomOAuth2UserService.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/member/controller/MemberController.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/resources/templates/view/reward/confirmForm.html
  src/main/resources/templates/view/reward/settingForm.html
Labels: refactoring

#85 스케줄링 서비스(챌린지의 종료, 챌린지 멤버의 종료, 생활지원금 지급)
  src/main/java/com/knj/mirou/MirouApplication.java
  src/main/java/com/knj/mirou/boundedContext/challenge/repository/ChallengeRepository.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/model/entity/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/point/entity/Point.java
  src/main/java/com/knj/mirou/boundedContext/point/service/PointService.java
Labels: enhancement

#87 챌린지 라벨 세팅 및 라벨을 통한 유효 인증 처리
  src/main/java/com/knj/mirou/base/controller/HomeController.java
  src/main/java/com/knj/mirou/base/initData/ForProd.java
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/config/LabelConfig.java
  src/main/java/com/knj/mirou/boundedContext/challenge/config/LabelConfigProperties.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/dtos/ChallengeCreateDTO.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengeLabel.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengeTag.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/imageData/service/ImageDataService.java
  src/main/java/com/knj/mirou/boundedContext/member/service/MemberService.java
  src/main/java/com/knj/mirou/boundedContext/reward/controller/RewardController.java
  src/main/resources/application-secret.default
  src/main/resources/templates/view/challenge/createForm.html
Labels: enhancement

#91 전체 챌린지 리스트 페이지 프론트작업
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/repository/ChallengeMemberRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/model/enums/OptimizerOption.java
  src/main/resources/templates/view/challenge/list.html
Labels: Front

#89 CSRF 토큰 처리 및 UI 개선
  src/main/java/com/knj/mirou/base/security/SecurityConfig.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/dtos/ChallengeDetailDTO.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/model/entity/ChallengeMember.java
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
  src/main/resources/templates/view/member/mypage.html
  src/main/resources/templates/view/reward/confirmForm.html
  src/main/resources/templates/view/reward/settingForm.html
Labels: refactoring

#95 현재 보유 포인트, 코인 출력 및 전체 챌린지 리스트 프론트 수정
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/resources/templates/view/challenge/list.html
Labels: refactoring, Front

#97 ChallengeFeed 관련 프론트 작업 및 좋아요, 신고하기 기능 간단 구현
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/dtos/ChallengeDetailDTO.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/model/dtos/FeedListDTO.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/model/entity/ChallengeFeed.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/repository/ChallengeFeedRepository.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/model/enums/OptimizerOption.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/controller/ReportHistoryController.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/entity/ReportHistory.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/repository/ReportHistoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/reportHistory/service/ReportHistoryService.java
  src/main/resources/templates/view/challenge/detail.html
  src/main/resources/templates/view/challengeFeed/detail.html
  src/main/resources/templates/view/challengeFeed/list.html
Labels: enhancement, Front

#101 CoinHistory 프론트 출력
  src/main/java/com/knj/mirou/boundedContext/challengefeed/service/ChallengeFeedService.java
  src/main/java/com/knj/mirou/boundedContext/coin/service/CoinService.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/controller/CoinHistoryController.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/entity/CoinHistory.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/repository/CoinHistoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/service/CoinHistoryService.java
  src/main/java/com/knj/mirou/boundedContext/imageData/model/enums/OptimizerOption.java
  src/main/resources/templates/common/layout/exampleLayout.default
  src/main/resources/templates/view/coin/history.html
  src/main/resources/templates/view/member/mypage.html
Labels: enhancement, Front

#107 포인트 히스토리 간단기능 구현
  src/main/java/com/knj/mirou/boundedContext/pointhistory/controller/PointHistoryController.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/entity/PointHistory.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/repository/PointHistoryRepository.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/service/PointHistoryService.java
  src/main/resources/templates/view/challenge/list.html
  src/main/resources/templates/view/member/mypage.html
  src/main/resources/templates/view/point/history.html
Labels: enhancement

#116 일상지원금(포인트) 시나리오 구현
  src/main/java/com/knj/mirou/boundedContext/challengemember/controller/ChallengeMemberController.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
  src/main/java/com/knj/mirou/boundedContext/point/entity/Point.java
  src/main/java/com/knj/mirou/boundedContext/point/service/PointService.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/controller/PointHistoryController.java
Labels: enhancement

#106 상품, 상점 관련 기본 틀
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/product/model/entity/Product.java
  src/main/java/com/knj/mirou/boundedContext/product/repository/ProductRepository.java
  src/main/java/com/knj/mirou/boundedContext/product/service/ProductService.java
  src/main/java/com/knj/mirou/boundedContext/store/controller/StoreController.java
  src/main/java/com/knj/mirou/boundedContext/store/repository/StoreRepository.java
  src/main/java/com/knj/mirou/boundedContext/store/service/StoreService.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/view/admin/adminPage.html
  src/main/resources/templates/view/store/addForm.html
  src/main/resources/templates/view/store/storePage.html
Labels: enhancement

#114 Spring Security Remember Me(자동 로그인, 유지) 도입
  build.gradle
  src/main/java/com/knj/mirou/base/security/config/PersistentTokenConfig.java
  src/main/java/com/knj/mirou/base/security/config/SecurityConfig.java
  src/main/java/com/knj/mirou/base/security/entity/PersistentLogin.java
  src/main/java/com/knj/mirou/base/security/repository/JpaPersistentTokenRepository.java
  src/main/java/com/knj/mirou/base/security/repository/PersistentLoginRepository.java
  src/main/java/com/knj/mirou/base/security/service/CustomOAuth2UserService.java
  src/main/java/com/knj/mirou/base/security/service/CustomRememberMeService.java
  src/main/java/com/knj/mirou/base/security/service/CustomUserDetailsService.java
  src/main/resources/application.yml
Labels: enhancement

#118 전체 챌린지 리스트 최신순으로 정렬
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
Labels: refactoring

#120 지도 API 기반 주변 정보 받아오기
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/MapCategory.java
  src/main/resources/templates/view/challenge/mapTest.html
Labels: enhancement

#122 전체 챌린지 리스트에서 이미 참여한 챌린지 제거
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/AuthenticationMethod.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/MapCategory.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/service/ChallengeMemberService.java
Labels: refactoring

#123 위치 기반 챌린지 인증 서비스
  src/main/java/com/knj/mirou/base/initData/NotProd.java
  src/main/java/com/knj/mirou/boundedContext/challenge/controller/ChallengeController.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/dtos/ChallengeCreateDTO.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/AuthenticationMethod.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/MapCategory.java
  src/main/java/com/knj/mirou/boundedContext/challenge/service/ChallengeService.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/controller/ChallengeFeedController.java
  src/main/resources/application.yml
  src/main/resources/templates/view/challenge/createForm.html
  src/main/resources/templates/view/challenge/mapTest.html
  src/main/resources/templates/view/challengeFeed/mapWriteForm.html
  src/main/resources/templates/view/challengeFeed/writeForm.html
Labels: enhancement
