Repository Mirou-KnJ/Mirou_Main, pull requests merged in 2023-10, with the labels that each got.

#3 서버 MariaDB 연동, EnableJpaAuditing 어노테이션 추가, 테스트 의존성 추가
  build.gradle
  src/main/java/com/knj/mirou/MirouApplication.java
  src/main/resources/application.yml
Labels: documentation

#4 전체 엔티티작성
  src/main/java/com/knj/mirou/boundedContexts/challenge/Challenge.java
  src/main/java/com/knj/mirou/boundedContexts/challengefeed/ChallengeFeed.java
  src/main/java/com/knj/mirou/boundedContexts/challengemember/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContexts/coin/Coin.java
  src/main/java/com/knj/mirou/boundedContexts/coinhistory/CoinHistory.java
  src/main/java/com/knj/mirou/boundedContexts/member/Member.java
  src/main/java/com/knj/mirou/boundedContexts/point/Point.java
  src/main/java/com/knj/mirou/boundedContexts/pointhistory/PointHistory.java
  src/main/java/com/knj/mirou/boundedContexts/reward/Reward.java
Labels: enhancement

#11 전체 엔티티 구조 개선 및 BaseEntity 추가
  src/main/java/com/knj/mirou/base/entity/BaseEntity.java
  src/main/java/com/knj/mirou/base/enums/ChangeType.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/entity/Challenge.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengePeriod.java
  src/main/java/com/knj/mirou/boundedContext/challenge/model/enums/ChallengeStatus.java
  src/main/java/com/knj/mirou/boundedContext/challengefeed/entity/ChallengeFeed.java
  src/main/java/com/knj/mirou/boundedContext/challengemember/entity/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContext/coin/entity/Coin.java
  src/main/java/com/knj/mirou/boundedContext/coinhistory/entity/CoinHistory.java
  src/main/java/com/knj/mirou/boundedContext/member/model/entity/Member.java
  src/main/java/com/knj/mirou/boundedContext/member/model/enums/MemberRole.java
  src/main/java/com/knj/mirou/boundedContext/point/entity/Point.java
  src/main/java/com/knj/mirou/boundedContext/pointhistory/entity/PointHistory.java
  src/main/java/com/knj/mirou/boundedContext/reward/model/entity/Reward.java
  src/main/java/com/knj/mirou/boundedContext/reward/model/enums/RewardType.java
  src/main/java/com/knj/mirou/boundedContexts/challenge/Challenge.java
  src/main/java/com/knj/mirou/boundedContexts/challengefeed/ChallengeFeed.java
  src/main/java/com/knj/mirou/boundedContexts/challengemember/ChallengeMember.java
  src/main/java/com/knj/mirou/boundedContexts/coin/Coin.java
  src/main/java/com/knj/mirou/boundedContexts/coinhistory/CoinHistory.java
  src/main/java/com/knj/mirou/boundedContexts/member/Member.java
  src/main/java/com/knj/mirou/boundedContexts/point/Point.java
  src/main/java/com/knj/mirou/boundedContexts/pointhistory/PointHistory.java
  src/main/java/com/knj/mirou/boundedContexts/reward/Reward.java
Labels: enhancement, refactoring

#12 기본 프론트 레이아웃 틀 구성
  build.gradle
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/common/fragments/footer.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/common/layout/defaultLayout.html
  src/main/resources/templates/common/layout/exampleLayout.default
  src/main/resources/templates/view/index.html
Labels: enhancement
